name: Azure OIDC

# This is required to trigger the workflow manually.
on: [workflow_dispatch]

permissions:
  # This is required for requesting the JWT.
  id-token: write
  # This is required for actions/checkout.
  contents: read

jobs:

  # Authentication is valid in this job scope only.
  Azure-OIDC:
    runs-on: windows-latest
    environment: Vivek_Jindal_RG
    steps:

      - name: OIDC login to Azure Public Cloud with AzPowershell
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Azure login test
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzResourceGroup
          azPSVersion: "latest"
